apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podsec
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
# When you create the "monitoring-endpoints" ClusterRole,
# the rules below will be added to the "monitoring" ClusterRole.
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "list", "watch", "patch", "update", "create"]
