apiVersion: apps/v1
kind: Deployment
metadata:
  name: podsec
  namespace: podsec
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podsec
      app.kubernetes.io/instance: podsec
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podsec
        app.kubernetes.io/instance: podsec
    spec:
      serviceAccountName: podsec
      containers:
        - name: podsec
          image: aliaj88/podsec:1
          imagePullPolicy: "IfNotPresent"

